### ISSUE TITLE
unable to build fuseide help plugin with java jdk 1.7-75 and maven 3.2.5

### ISSUE THREAD

**Issue by ronnyaerts** [fusesource/fuseide#143] opened 2015-03-06 15:40 UTC
I upgraded my java to the lastest jdk 1.7-75 and maven to 3.2.5 version. I cloned the git repository to a local drive and executed a "mvn clean package -Dmaven.test.skip=true" command. 
This gives and error on the Help plugin and the rest of the build is skipped. 
[INFO] JBoss Fuse Tooling :: Core :: Plugins :: Help ...... FAILURE [ 19.401 s]

I also see:
[WARNING] Error injecting: org.apache.maven.plugin.antrun.AntRunMojo
java.lang.NoClassDefFoundError: org/apache/tools/ant/BuildException
...
Caused by: java.lang.ClassNotFoundException: org.apache.tools.ant.BuildException
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:17 min
[INFO] Finished at: 2015-03-06T16:34:36+01:00
[INFO] Final Memory: 165M/655M

**Comment by ronnyaerts** [comment] 2015-03-06 16:05
I added <version>1.8</version> after <artifactId>maven-antrun-plugin</artifactId>.in the .\core\plugins\org.fusesource.ide.help\pom.xml and then the build process continues.

**Comment by lhein** [comment] 2015-03-09 08:06
Hey,
that sounds really odd. I use mvn 3.2.5 too and tried both Java 7 and 8 and both built fine.
Any chance that you have some odd PATH variable in your system?

Lars

**Comment by ronnyaerts** [comment] 2015-03-09 08:09
Hello Lars,

I don’t have any odd path as far as I know.

C:\Users\RRTS.INTRIS>set path
Path=C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\PHP;%CommonProgramFiles%\Microsoft Shared\Windows Live;C:\windows\system32;C:\windows;
C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommo
n;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Git\bin;C:\sysprogs\GitStack\python;C:\sysprogs\GitStack\python\Scripts;C:\sysprogs\GitStack\p
hp;C:\sysprogs\GitStack\git\cmd;C:\sysprogs\GitStack\git\bin;C:\Program Files (x86)\Mail Enable\Bin64;C:\Program Files\TortoiseGit\bin;C:\Users\RRTS.I
NTRIS\Dropbox\Utilities\exec;C:\Program Files (x86)\GIT\cmd;C:\Program Files (x86)\Java\jre6\bin;C:\Program Files (x86)\OpenVPN\bin;C:\sysprogs\apache
-maven-3.2.5\bin
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
--
vriendelijke groeten,
Ronny Aerts<mailto:ronny.aerts@intris.be> – Intris nv – Wapenstilstandlaan 47, 2600 Berchem, België
R&D Integration Architect
Prince II<http://nl.wikipedia.org/wiki/PRINCE2> certified – ITIL<http://nl.wikipedia.org/wiki/Information_Technology_Infrastructure_Library> certified
Tel: +32-3-326.50.75

**Comment by lhein** [comment] 2015-03-09 08:14
You said that you are using Java7. Why is there JRE 6 in your PATH settings? Thats not a good thing as you are mixing Java versions. Is C:\ProgramData\Oracle\Java\javapath the location where your Java7 lives? Because I can't see any Java7 path in your variable besides that.

**Comment by ronnyaerts** [comment] 2015-03-09 08:17
Hallo Lars,

I have to mix java versions for several other projects. I explicitly do a “set java_home=C:\Program Files\Java\jdk1.7.0_75”.

--
vriendelijke groeten,
Ronny Aerts<mailto:ronny.aerts@intris.be> – Intris nv – Wapenstilstandlaan 47, 2600 Berchem, België
R&D Integration Architect
Prince II<http://nl.wikipedia.org/wiki/PRINCE2> certified – ITIL<http://nl.wikipedia.org/wiki/Information_Technology_Infrastructure_Library> certified
Tel: +32-3-326.50.75

**Comment by lhein** [comment] 2015-03-09 08:24
Thats ok, but the point is if the JRE 6 is always in your PATH variable it can be used at any time by java or maven when accessing a Java binary or library. Therefor I strongly suggest only having the java path in your PATH variable which you currently use. Windows is really poor when it comes to working with different Java envs. Have a look at https://blogs.oracle.com/pranav/entry/switch_between_different_jdk_v for how a switch could look like. But before that you should remove all Java stuff from the PATH variable as this is not a user variable but a system variable.
Also keep  in mind that this will only affect the current shell. 

But maybe lets first test if those PATH entries really cause the issue. Try remove the JRE6 from the PATH. Also remove that C:\ProgramData\Oracle\Java\javapath.
Then in a shell set your JAVA_HOME and also the PATH for your Java7 like in the linked blog entry.
Then build the tooling.

**Comment by ronnyaerts** [comment] 2015-03-09 10:35
Hallo Lars,

The C:\ProgramData\Oracle\Java\javapath seems to be a method of the java installer to set the “active” java version. The folder contains 3 shortcuts (java, javaw and javaws) to the newest installed java which is C:\Program Files\Java\jre1.8.0_31\bin\java.exe is my case.

I stripped my path to:
Path=C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Git\bin;C:\sysprogs\GitStack\python;C:\sysprogs\GitStack\python\Scripts;C:\sysprogs\GitStack\php;C:\sysprogs\GitStack\git\cmd;C:\sysprogs\GitStack\git\bin;C:\Program Files\TortoiseGit\bin;C:\Users\RRTS.INTRIS\Dropbox\Utilities\exec;C:\Program Files\java\jdk1.7.0_75\bin;C:\sysprogs\apache-maven-3.2.5\bin

I think this action does not realy help because the java installer put a java.exe in the c:\windows\system32 folder. A “java -version" shows me:
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

I reverted the pom.xml of the help.
I executed:
C:\Users\RRTS.INTRIS>cd /d I:\TrisESB\fusetools\fuseide
I:\TrisESB\fusetools\fuseide>set java_home=C:\Program Files\Java\jdk1.7.0_75
I:\TrisESB\fusetools\fuseide> mvn clean package -Dmaven.test.skip=true

But no success. I get the same error. I attached to complete log.
--
vriendelijke groeten,
Ronny Aerts<mailto:ronny.aerts@intris.be> – Intris nv – Wapenstilstandlaan 47, 2600 Berchem, België
R&D Integration Architect
Prince II<http://nl.wikipedia.org/wiki/PRINCE2> certified – ITIL<http://nl.wikipedia.org/wiki/Information_Technology_Infrastructure_Library> certified
Tel: +32-3-326.50.75

**Comment by lhein** [comment] 2015-03-09 10:42
Wow, I have to admit that I am not really deep into Windows stuff. I
will try to setup a windows box here to see if I can reproduce your problem.

Lars


Am 09.03.2015 um 11:35 schrieb ronnyaerts:

**Comment by apupier** [comment] 2016-01-13 15:19
Hi ronnyaerts,

after all this time I tried on windows 10, Maven 3.3.3 and java 1.7.0_79 and it works fine for me.

I tested on the master.
Can you try to reproduce on the current branch please?

regards,

**Comment by apupier** [comment] 2016-01-19 07:47
I close this issue. If you still encounter the issue please reopen providing more details;

**Closed by apupier** 2016-01-19 07:47 UTC
