### ISSUE TITLE
install JBoss Fuse Tooling in eclipse luna gives errors

### ISSUE THREAD

**Issue by ronnyaerts** [fusesource/fuseide#165] opened 2015-03-23 11:15 UTC
I tried to install the plugins into eclipse luna but failed. 

I downloaded the "Eclipse IDE for Java EE Developers" 64-bit on a windows 8.1 as well as a windows 7 64-bit machine. 
I installed the all plugins from http://download.jboss.org/jbosstools/updates/integration/luna/integration-stack/fuse-tooling/7.3.0/all/repo/ and after some time I get:
Cannot complete the install because one or more required items could not be found.
  Software being installed: JBoss Fuse Tooling Server Adapters Developer Resources 7.3.0.v20150320-1714-H395-MASTER (org.fusesource.ide.server.extensions.feature.source.feature.group 7.3.0.v20150320-1714-H395-MASTER)
  Missing requirement: JBoss Fuse Tooling Server Adapters 7.3.0.v20150320-1714-H395-MASTER (org.fusesource.ide.server.extensions.feature.feature.group 7.3.0.v20150320-1714-H395-MASTER) requires 'org.jboss.ide.eclipse.as.wtp.core 3.0.0' but it could not be found
  Cannot satisfy dependency:
    From: JBoss Fuse Tooling Server Adapters Developer Resources 7.3.0.v20150320-1714-H395-MASTER (org.fusesource.ide.server.extensions.feature.source.feature.group 7.3.0.v20150320-1714-H395-MASTER)
    To: org.fusesource.ide.server.extensions.feature.feature.group [7.3.0.v20150320-1714-H395-MASTER]

I don't get this error if I first install the "JBoss Tools (Luna) 4.2.2 final" from the eclipse marketplace.

Is this normal behavior?

**Comment by lhein** [comment] 2015-03-23 12:40
Hi Ronny,

our server adapters use code from the JBoss Tools platform so you need to install JBoss Tools before you can install Fuse Tooling. We also have another dependency called "gemini" which needs to be available.
Easiest is really to start by taking JBDS 8 as base and then use JBoss Central to install the Integration Stack (if you want to install Fuse from nightly it makes sense to not install it as part of the Integration Stack).

Lars

**Comment by lhein** [comment] 2015-03-24 18:59
Closing this issue as its not a bug.

**Closed by lhein** 2015-03-24 18:59 UTC
